version: "3.4"

services:
  ms-python-hello:
    container_name: ms-python-hello
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - 8181:8000
    env_file:
      - ./database.env
    links:
      - ms-python-redis
    command: ./wait-for.sh ms-python-redis:6379 -- gunicorn -b 0.0.0.0 --reload -w 4 server:app

  ms-python-redis:
    container_name: ms-python-redis
    image: redis:5-alpine
    ports:
      - 16379:6379
    env_file:
      - ./database.env
    volumes:
      - ms_python_db_data:/etc/redis/database
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  ms_python_db_data: